import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const config: Config = {
  title: 'Study Mate',
  tagline: 'Learn books interactively — concepts, live visualizations, and flashcards',
  favicon: 'img/favicon.ico',

  future: {
    v4: true,
  },

  url: 'https://study-mate.local',
  baseUrl: '/',

  organizationName: 'study-mate',
  projectName: 'interactive-book',

  // Generated cross-links can occasionally drift; warn instead of failing the build.
  onBrokenLinks: 'warn',
  onBrokenMarkdownLinks: 'warn',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          // The interactive book IS the site — serve docs at the root.
          routeBasePath: '/',
          sidebarPath: './sidebars.ts',
          // No edit links — these pages are generated, not hand-authored.
          editUrl: undefined,
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    image: 'img/docusaurus-social-card.jpg',
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'Study Mate',
      logo: {
        alt: 'Study Mate',
        src: 'img/logo.svg',
      },
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'booksSidebar',
          position: 'left',
          label: 'Books',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [],
      copyright: `Generated by Study Mate · Built with Docusaurus · ${new Date().getFullYear()}`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
