import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One sidebar, autogenerated from the docs/ tree. Each book is a folder with a
// _category_.json (written by the generator); the landing page (docs/intro.mdx,
// slug "/") sits at the top.
const sidebars: SidebarsConfig = {
  booksSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
