#!/usr/bin/env bash
# Static checks for marimo notebooks generated by /learn-book.
# Catches the four bug classes (R1, R3, R4, R5) that are invisible to `marimo check`
# but break the WASM runtime. Exit 0 if clean; exit 1 if any pattern matches.
set -u

if [ "$#" -lt 1 ]; then
  echo "usage: $0 <notebook.py>" >&2
  exit 2
fi

FILE="$1"
if [ ! -f "$FILE" ]; then
  echo "static-checks: file not found: $FILE" >&2
  exit 2
fi

violations=0

check () {
  local label="$1" pattern="$2"
  local hits
  # Strip pure comment lines and docstring-delimiter lines before matching, so
  # mentions of forbidden names inside docs (e.g. `"""no scipy"""`) don't
  # trigger false positives. We keep the original line numbers via grep -n.
  hits="$(grep -nE "$pattern" "$FILE" \
    | grep -vE '^[0-9]+:[[:space:]]*#' \
    | grep -vE '^[0-9]+:[[:space:]]*("""|'\'''\'''\'')' \
    || true)"
  if [ -n "$hits" ]; then
    echo "[FAIL] $label"
    echo "$hits" | sed 's/^/        /'
    violations=$((violations+1))
  fi
}

# R3: _-prefixed name returned across cells, e.g. `return (_foo,)` or `return _foo, _bar`
check "R3 (_-prefixed cross-cell return)" "return.*\(_[a-z][a-z_0-9]*[,)]"

# R4: chained .value off mo.ui.X(...) inside the same cell
check "R4 (same-cell .value access)" "mo\.ui\.[a-z]+\([^)]*\)\.value"

# R1+R6: forbidden libraries / scipy-requiring networkx calls
check "R1/R6 (forbidden lib or scipy-requiring nx call)" "\\b(scipy|pandas|plotly|sklearn|seaborn|spring_layout|kamada_kawai|to_scipy_sparse_array)\\b"

# R5: tuple-expression returns of marimo render objects
check "R5 (tuple-expression return)" "return mo\\.(md|vstack|hstack|callout|image)\\([^)]*\\),[[:space:]]*mo\\."

if [ "$violations" -eq 0 ]; then
  exit 0
fi
exit 1
